import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const output='assets/demo';await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1600,height:1240},deviceScaleFactor:1,recordVideo:{dir:'/tmp/clitorisophila-video',size:{width:1440,height:1080}}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8771/?autoload');
await page.waitForFunction(()=>window.clitorisophila?.ready,null,{timeout:120000});
const button=page.locator('#stimulate');
await button.focus();
await page.keyboard.down('Space');
await page.waitForFunction(()=>window.clitorisophila.lastRow?.reward_spikes>0,null,{timeout:10000});
await page.waitForTimeout(120);
await page.screenshot({path:output+'/live-stimulation.png'});
await page.keyboard.up('Space');
await page.waitForTimeout(500);
await page.click('#contact-size');
await page.locator('#contact-size').fill('0.35');
await page.locator('#contact-size').dispatchEvent('input');
await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(250);
await page.click('#focus');
await page.waitForTimeout(150);
await page.screenshot({path:output+'/circuit-detail.png'});
await page.keyboard.up('Space');await page.click('#focus');
await page.click('#auto');await page.waitForTimeout(9000);await page.click('#auto');
await page.screenshot({path:output+'/artwork-page.png',fullPage:true});
const state=await page.evaluate(()=>({ready:window.clitorisophila.ready,row:window.clitorisophila.lastRow,neurons:window.clitorisophila.manifest.neurons,connections:window.clitorisophila.manifest.connections}));
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
await page.screenshot({path:output+'/mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
console.log(JSON.stringify({errors,overflow,state}));
const video=page.video();await page.close();await context.close();
const path=await video.path();console.log('VIDEO',path);await fs.writeFile('/tmp/clitorisophila-video-path',path);
await browser.close();
